### ISSUE TITLE
Sprite Reference

### ISSUE THREAD

**Issue by Kaorixsol** [ByronMayne/AssetPathAttribute#3]

**Comment by Kaorixsol** [comment]
Hello, I found that Sprite only stores the path of the texture and does not store the SpriteName, so there is a problem when loading the Sprite in the game. In addition, the EditorGUI.ObjectField provided by Unity does not return sprite name information.

<img width="631" alt="qq20190118-102408 2x" src="https://user-images.githubusercontent.com/20392465/51361628-874be900-1b0b-11e9-8285-c2acb9ae3714.png">

`EditorGUI.BeginChangeCheck();
        {
            // Draw our object field.
            propertyValue = EditorGUI.ObjectField(position, label, propertyValue, objectType, false);
        }`

**Comment by Kaorixsol** [comment]
I might be able to use EditorGUIUtility.ShowObjectPicker
EditorGUIUtility.GetObjectPickerObject

**Comment by ByronMayne** [comment]
Hey JinFengJi, 

Sprites are a weird asset in Unity because they don't have a path in the AssetDatabase. Behind the scenes sprites are just a location on a texture. So if you wanted to store them as an asset path you would need to store two unique pieces of information. This means you either have to change AssetPath to target objects with both a asset path and sprite name or just combine both into the serialized string. Both of these are really not ideal. What I do is I make my own type called SpriteReference which is a complex type with it's own editor.
