### ISSUE TITLE
when move the prefab into a new folder ,the reference missing .

### ISSUE THREAD

**Issue by Bian-Sh** [ByronMayne/AssetPathAttribute#4]
Unity 2019.2.12f1
you can reproduce by these steps：
1. Sign a prefab into AssetPath field.
2. Create a new folder beside this prefab
3. move the prefab into the new folder you'v created above。
4. then you will find that the reference of that prefab is missing from the assetpath field where you used to have signed before.

**Comment by ByronMayne** [comment]
Hey Bian-Sh,

Short Answer: This is expected due to the nature of storing paths. 
Long Answer: AssetPath stores relative paths to assets inside your Unity folder. When you look at object in the inspector the custom property drawer is creating fake UI which looks like an object reference.  When you are not viewing an asset path in the inspector literally nothing is running.

If you move a object that has it's path stored the path will become invalid, as expected.

**Comment by Bian-Sh** [comment]
hey ByronMayne:
1. I think we can improve the bad user experience by create a simple database which can store the very keyvaluepair of path and guid. 
2. When you find that  the path is invalid,then ,you can get the guid from the simple database you have had made before by using the old path 
3. as far as i know, guid is never changed once it has been created. with this guid we can track the assets again ,get the new path and replace the orign keyvaluepair with the new one.
3. and the simple database could be any serialize solution is ok ,perhaps json ,yaml, protobuf , xml , sqlite and so on.

**Comment by ByronMayne** [comment]
The issue is this is a custom inspector which means the logic only runs when you are looking at the asset.

 Storing that information in a database is not great because you also have to map every asset that references and asset with a guid. 

The better option is to not store paths at all but store a guid and only replace the path at compile time. 

These are out if scope for the asset path attribute

**Comment by Bian-Sh** [comment]
>The better option is to not store paths at all but store a guid and only replace the path at compile time.

cant aggree any more , 

但我觉得值得去实现一下，虽然可能编译时获取并修改 SceneAssets PrefabAssets 可能有点困难。

But I think it's worth implementing, although it might be a little difficult to get and modify SceneAssets PrefabAssets at compile time

**Comment by laurentopia** [comment]
> Short Answer: This is expected due to the nature of storing paths. Long Answer: AssetPath stores relative paths to assets inside your Unity folder. When you look at object in the inspector the custom property drawer is creating fake UI which looks like an object reference. When you are not viewing an asset path in the inspector literally nothing is running.
> 
> If you move a object that has it's path stored the path will become invalid, as expected.

see https://github.com/JohannesMP/unity-scene-reference on how it's done
